# Generated by Django 3.2.25 on 2024-04-13 17:16

import Contact.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_alter_contact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=Contact.models.LessStrictURLField(),
        ),
    ]
